/*-----------------Personnel-------8 departments * 10 permits * 5 = 400 rows ------------------*/
/* the dataset focus on ECA of 8 departments (4 hospital: IdEstablishment == 23,24,29,54 (IdAddress == 3,4,9,34) ;
4 medical clinics: IdEstablishment == 25,39,46,56  (IdAddress == 5,19,26,36))

select * from "Establishment" where "Name"='hospital';
select * from "Establishment" where "Name"='medical clinics';
 */
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (1, '1', 'Satyford', 'Megen', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (2, '2', 'Snowsill', 'Merrilee', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (3, '3', 'Slides', 'Linn', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (4, '4', 'Colliver', 'West', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (5, '5', 'Woodsford', 'Meridel', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (6, '6', 'Erickson', 'Kyrstin', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (7, '7', 'Hatherall', 'Zachariah', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (8, '8', 'Johanning', 'Meredith', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (9, '9', 'Sellstrom', 'Philly', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (10, '10', 'Ghent', 'Orville', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (11, '11', 'Pelerin', 'Benoit', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (12, '1', 'Swansbury', 'Katrinka', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (13, '2', 'England', 'Miguelita', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (14, '3', 'Gettings', 'Maud', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (15, '4', 'Ferraro', 'Blinny', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (16, '5', 'Meegan', 'Coletta', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (17, '6', 'Fish', 'Fancy', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (18, '7', 'Tower', 'Darcee', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (19, '8', 'Mosco', 'Gothart', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (20, '9', 'Bradtke', 'Greg', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (21, '10', 'Tansley', 'Lila', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (22, '11', 'Oppie', 'Starlin', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (23, '1', 'Kealy', 'Pavla', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (24, '2', 'Cuckson', 'Edd', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (25, '3', 'Laxson', 'Gerrard', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (26, '4', 'Reef', 'Mil', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (27, '5', 'Wadley', 'Marylin', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (28, '6', 'Graber', 'Nelle', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (29, '7', 'Weathers', 'Seline', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (30, '8', 'Wilshire', 'Jordana', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (31, '9', 'Owthwaite', 'Alvin', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (32, '10', 'Sabban', 'Ethelin', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (33, '11', 'Fields', 'Ruttger', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (34, '1', 'Devonald', 'Gordy', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (35, '2', 'Kingaby', 'Jess', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (36, '3', 'McGurgan', 'Kermie', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (37, '4', 'Dupree', 'Ashton', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (38, '5', 'Pavluk', 'Jerome', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (39, '6', 'Bingall', 'Shandeigh', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (40, '7', 'Giacomelli', 'Jewelle', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (41, '8', 'Worsom', 'Ingeberg', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (42, '9', 'Ireland', 'Elston', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (43, '10', 'Darragon', 'Tobiah', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (44, '11', 'Demchen', 'Jaimie', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (45, '1', 'Kornes', 'Alison', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (46, '2', 'Mc Cahey', 'Correy', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (47, '3', 'Wrassell', 'Gracie', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (48, '4', 'Champion', 'Virgina', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (49, '5', 'Bestwerthick', 'Zorana', 3);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (50, '6', 'Aronovich', 'Verine', 3);

insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (51, '7', 'Hutchison', 'Bronson', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (52, '8', 'Di Giacomettino', 'Sabra', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (53, '9', 'Cossum', 'Michal', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (54, '10', 'Ugoni', 'Sidonnie', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (55, '11', 'Riccardi', 'Dov', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (56, '1', 'Howroyd', 'Ilene', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (57, '2', 'Ekins', 'Allen', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (58, '3', 'Kelley', 'Armand', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (59, '4', 'Sammes', 'Eugene', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (60, '5', 'Croote', 'Jephthah', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (61, '6', 'Munton', 'Sharline', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (62, '7', 'Manchester', 'Peria', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (63, '8', 'Scrowston', 'Bud', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (64, '9', 'Kleinstern', 'Galvan', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (65, '10', 'Boothby', 'Darla', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (66, '11', 'Crucitti', 'Colet', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (67, '1', 'Daal', 'Kenyon', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (68, '2', 'Eldred', 'Zorana', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (69, '3', 'Angeli', 'Tanner', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (70, '4', 'Giraudot', 'Harlen', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (71, '5', 'Trobridge', 'Codee', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (72, '6', 'Dobing', 'Ag', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (73, '7', 'Cruft', 'Jo', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (74, '8', 'Chadwen', 'Todd', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (75, '9', 'Skittrell', 'Silvan', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (76, '10', 'Domek', 'Guglielma', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (77, '11', 'Stennine', 'Holli', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (78, '1', 'Seaton', 'Phillis', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (79, '2', 'Yeabsley', 'Chelsea', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (80, '3', 'Flade', 'Rudie', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (81, '4', 'MacMichael', 'Bill', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (82, '5', 'Killner', 'Lynn', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (83, '6', 'Thame', 'Ki', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (84, '7', 'Bonin', 'Nissy', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (85, '8', 'Bissatt', 'Hussein', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (86, '9', 'Salamon', 'Dorella', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (87, '10', 'Hatchell', 'Hardy', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (88, '11', 'Goney', 'Karlen', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (89, '1', 'Malinson', 'Freddy', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (90, '2', 'Atton', 'Marta', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (91, '3', 'Bridgeman', 'Sampson', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (92, '4', 'Shoutt', 'Errick', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (93, '5', 'Fannin', 'Ennis', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (94, '6', 'Geroldini', 'Mariam', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (95, '7', 'Locket', 'Dawna', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (96, '8', 'Gianinotti', 'Blayne', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (97, '9', 'Duckers', 'Blake', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (98, '10', 'Bygrove', 'Damaris', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (99, '11', 'Oxberry', 'Boone', 4);
insert into "ECA" ("Id", "IdTypeECA", "Lastname", "Firstname", "IdAddress") values (100, '1', 'Jirick', 'Ebeneser', 4);